# Generated by Django 5.1.3 on 2024-11-21 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_customer', models.CharField(blank=True, max_length=255, verbose_name='')),
                ('image', models.ImageField(upload_to='cover/', verbose_name='image')),
                ('date_time_created', models.DateTimeField(auto_now_add=True, verbose_name='date created')),
            ],
            options={
                'verbose_name': 'portfolio',
                'verbose_name_plural': 'portfolio',
            },
        ),
    ]
