# Generated by Django 5.1.3 on 2024-11-21 08:59

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='portfolio',
            options={'verbose_name': 'نمونه کارها', 'verbose_name_plural': 'نمونه کارها'},
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='date_time_created',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاریخ'),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='image',
            field=models.ImageField(upload_to='cover/', verbose_name='تصویر'),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='name_customer',
            field=models.CharField(blank=True, max_length=255, verbose_name='نام مشتری '),
        ),
    ]
