# Generated by Django 5.1.3 on 2024-11-21 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_portfolio_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer_call',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100, verbose_name='full name')),
                ('phone_number', models.CharField(max_length=11, verbose_name='phone number')),
                ('message', models.TextField(verbose_name='message')),
                ('date_time_send_message', models.DateTimeField(auto_now_add=True, verbose_name='date send message')),
            ],
            options={
                'verbose_name': 'message from user',
                'verbose_name_plural': 'message from user',
            },
        ),
    ]
